filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logstash-tutorial.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 3

output.logstash:
  hosts: ["192.168.0.144:5044"]
