version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    container_name: elasticsearch
    restart: always
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    container_name: elasticsearch2
    restart: always
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
  
  logstash:
    image: docker.elastic.co/logstash/logstash:6.8.0
    container_name: logstash
    restart: always
    volumes:
      - ./config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./config/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - 5044:5044
    environment:
      LS_JAVA_OPS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch


  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.0
    container_name: kibana
    restart: always
    environment: 
      - "ELASTICSEARCH_URL=http://192.168.0.144:9200"
    ports:
     - 5601:5601
    depends_on:
     - elasticsearch

  nginx:
     image: nginx
     container_name: nginx
     restart: always
     volumes:
       - ./config/nginx/config/:/etc/nginx/conf.d/
      # - ./nginx/config/test-kibana.zhigui.com.conf:/etc/nginx/conf.d/
     ports:
       - "80:80"
       - "443:443"

networks:
  esnet:
    driver: bridge
