version: '2.2'
services:
   filebeat:
     image: docker.elastic.co/beats/filebeat:6.8.0
     container_name: filebeat
     volumes:
        - ./config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
        - /root/efk/src/logstash-tutorial.log:/usr/share/filebeat/logstash-tutorial.log
